# Generated by Django 5.2.8 on 2025-12-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
