# Generated by Django 5.0.2 on 2026-02-02 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sosalert_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='preferred_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='preferred_hospital_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
