# Generated by Django 5.0.2 on 2026-02-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('donor', 'Donor'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='donor', max_length=10),
        ),
    ]
