# Generated by Django 5.0.2 on 2026-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sosalert_donor_responder_sosalert_donor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='donor_availability',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available')], default='pending', max_length=10),
        ),
    ]
