# Generated by Django 5.0.2 on 2026-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_blood_group_user_donor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='donor_availability',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending')], default='available', max_length=10),
        ),
    ]
