# Generated by Codex on 2026-02-10

from django.db import migrations


def set_donor_availability_available(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(role='donor', donor_availability__in=['pending', '']).update(donor_availability='available')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_donor_availability'),
    ]

    operations = [
        migrations.RunPython(set_donor_availability_available, noop_reverse),
    ]

