# Generated by Django 5.0.2 on 2026-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_patient_role_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('donor', 'Donor'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='donor', max_length=10),
        ),
    ]
