# Generated by Django 4.2 on 2026-02-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
